import { describe, test, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import {
  initDB, closeDB, createConversation, createRun, addTraceEvent,
  completeRun,
} from '../memory/store.js';
import {
  createCampaign, createCampaignGoal, linkGoalRun, recordEvaluatorResult,
} from './campaign-store.js';
import {
  buildCampaignReplay, renderCampaignMarkdownReport,
  generateCampaignReport, generateCampaignEvidenceBundle,
} from './campaign-replay.js';

function seedCampaignWithOneRun() {
  initDB(':memory:');
  const conv = createConversation('replay-test');
  const campaign = createCampaign({
    title: 'Recon Sweep',
    objective: 'Map the lab perimeter and surface safe findings.',
    toolpackIds: ['web-recon', 'reporting'],
    workerBackend: 'phantom-native',
  });
  const goal = createCampaignGoal({
    campaignId: campaign.id,
    title: 'Resolve hostnames',
    prompt: 'Run resolve_hostname over the lab targets.',
  });
  const run = createRun({
    conversationId: conv.id,
    title: 'Resolve hostnames',
    goal: goal.prompt,
    model: 'mock',
  });
  linkGoalRun({ campaignId: campaign.id, goalId: goal.id, runId: run.id });
  addTraceEvent(run.id, { type: 'tool.call.started', phase: 'general', status: 'started' });
  addTraceEvent(run.id, { type: 'tool.call.completed', phase: 'general', status: 'completed' });
  completeRun(run.id, 'Done', { tokens_used: 0 });
  recordEvaluatorResult(goal.id, { decision: 'complete', summary: 'no findings; benign run' });
  return { campaign, goal, run };
}

describe('campaign-replay', () => {
  afterEach(() => closeDB());

  test('buildCampaignReplay rolls up goals + runs + summary', () => {
    const { campaign } = seedCampaignWithOneRun();
    const replay = buildCampaignReplay(campaign.id);
    assert.strictEqual(replay.campaign.id, campaign.id);
    assert.strictEqual(replay.goals.length, 1);
    assert.strictEqual(replay.runs.length, 1);
    assert.strictEqual(replay.summary.totalRuns, 1);
    assert.strictEqual(replay.runs[0].evaluator.decision, 'complete');
    assert.strictEqual(replay.summary.budgetUsed.maxRuns, replay.campaign.run_budget.maxChildRuns);
  });

  test('buildCampaignReplay throws on unknown id', () => {
    initDB(':memory:');
    assert.throws(() => buildCampaignReplay('does-not-exist'), /campaign not found/);
  });

  test('renderCampaignMarkdownReport contains header + goal + run rows', () => {
    const { campaign, goal, run } = seedCampaignWithOneRun();
    const replay = buildCampaignReplay(campaign.id);
    const md = renderCampaignMarkdownReport(replay);
    assert.match(md, /# Campaign: Recon Sweep/);
    assert.match(md, /Resolve hostnames/);
    assert.match(md, new RegExp(run.id.slice(0, 8)));
    assert.match(md, /Generated by PHANTOM campaign-replay/);
  });

  test('generateCampaignReport persists a markdown artifact tagged with campaignId', () => {
    const { campaign } = seedCampaignWithOneRun();
    const art = generateCampaignReport(campaign.id);
    assert.strictEqual(art.type, 'markdown');
    assert.match(art.title, /Campaign report/);
    // metadata is stored as JSON — read it back via the public artifact
    const meta = typeof art.metadata === 'string' ? JSON.parse(art.metadata) : art.metadata;
    assert.strictEqual(meta.source, 'campaign_report');
    assert.strictEqual(meta.campaignId, campaign.id);
  });

  test('generateCampaignEvidenceBundle persists a zip artifact', () => {
    const { campaign } = seedCampaignWithOneRun();
    const art = generateCampaignEvidenceBundle(campaign.id);
    assert.strictEqual(art.type, 'evidence');
    assert.strictEqual(art.mime_type || art.mimeType, 'application/zip');
    const meta = typeof art.metadata === 'string' ? JSON.parse(art.metadata) : art.metadata;
    assert.strictEqual(meta.source, 'campaign_evidence_bundle');
    assert.strictEqual(meta.campaignId, campaign.id);
  });

  test('generateCampaignReport refuses when the campaign has no child runs', () => {
    initDB(':memory:');
    const c = createCampaign({ title: 'Empty', objective: 'nothing yet' });
    assert.throws(() => generateCampaignReport(c.id), /before any child run/);
    assert.throws(() => generateCampaignEvidenceBundle(c.id), /before any child run/);
  });
});
